/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FavoriteId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFavoritePrayer' : IDL.Func(
      [FavoriteId],
      [IDL.Text, IDL.Vec(FavoriteId)],
      [],
    ),
  'addFavoriteQuote' : IDL.Func(
      [FavoriteId],
      [IDL.Text, IDL.Vec(FavoriteId)],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearFavorites' : IDL.Func([], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavorites' : IDL.Func(
      [],
      [
        IDL.Record({
          'quotes' : IDL.Vec(FavoriteId),
          'prayers' : IDL.Vec(FavoriteId),
        }),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFavoritePrayer' : IDL.Func([FavoriteId], [IDL.Vec(FavoriteId)], []),
  'removeFavoriteQuote' : IDL.Func([FavoriteId], [IDL.Vec(FavoriteId)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FavoriteId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFavoritePrayer' : IDL.Func(
        [FavoriteId],
        [IDL.Text, IDL.Vec(FavoriteId)],
        [],
      ),
    'addFavoriteQuote' : IDL.Func(
        [FavoriteId],
        [IDL.Text, IDL.Vec(FavoriteId)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearFavorites' : IDL.Func([], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavorites' : IDL.Func(
        [],
        [
          IDL.Record({
            'quotes' : IDL.Vec(FavoriteId),
            'prayers' : IDL.Vec(FavoriteId),
          }),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFavoritePrayer' : IDL.Func([FavoriteId], [IDL.Vec(FavoriteId)], []),
    'removeFavoriteQuote' : IDL.Func([FavoriteId], [IDL.Vec(FavoriteId)], []),
  });
};

export const init = ({ IDL }) => { return []; };